export const energyList = [
  "Tradition", "Restriction", 
"Decisions", "Lack of Planning", 
"Self-expression", "Ignorance",
"Idealism", "Moodiness",
"Inspiration", "Lack of Motivation",
"Abundance", "Smothering",
"Resilience", "Fatigue",
"Perseverance", "Giving Up",
"Manifestation", "Manipulation",
"Transformation", "Resistance",
"Abundance", "Loneliness",
"Compassion", "Unresolved Pain",
"Stability", "Rigidity",
"Family", "Unhappiness",
"Curiosity", "Miscommunication",
"Balance", "Confusion",
"Sacrifice", "Stagnation",
"Truth", "Blocked Ideas",
"Adventure", "Recklessness",
"Celebration", "Lack of Support",
"Nurturing", "Neglect",
"Expansion", "Delays",
"Courage", "Jealousy",
"Contemplation", "Action",
"Family", "Instability",
"Mystery", "Confusion",
"Patience", "Insecurity",
"Purification", "Negativity",
"Conflict", "Forgiveness",
"Adaptability", "Overwhelm",
"Assertiveness", "Recklessness",
"Spontaneity", "Recklessness",
"Intuition", "Insecurity",
"Entrepreneur", "Impatience",
"Opportunity", "Missed Opportunities",
"Isolation", "Hope",
"Moving On", "Resistance",
"Celebration", "Lack of Support",
"Worry", "Hope",
"Patience", "Lack of Progress",
"Karma", "Resistance",
"Celebration", "Unfulfilled Expectations",
"Preparation", "Anxiety",
"New Beginnings", "Instability",
"Amplification", "Dilution",
"Temptation", "Overcoming",
"Reflection", "Regret",
"Loss", "Moving On",
"Deception", "Honesty",
"Responsibility", "Overwhelm",
"Balance", "Imbalance",
"Victory", "Failure",
"Awakening", "Denial",
"Fast Paced", "Delays",
"Achievement", "Incompletion",
"Wishes Fulfilled", "Unfulfilled Desires",
"Meditation", "Burnout",
"Restriction", "Self-discovery",
"Determination", "Resistance to Change",
"Leadership", "Misuse of Power",
"Security", "Materialism",
"Moderation", "Excess",
"Manifestation", "Missed Opportunities",
"Charity", "Exploitation",
"Conflict", "Resentment",
"Partnership", "Separation",
"Emotional Growth", "Clinging to the Past",
"Intuition", "Doubt",
"Authority", "Manipulation",
"Vitality", "Temporary Setback",
"Independence", "Coldness",
"Inspiration", "Lack of Faith",
"Skill Development", "Lack of Focus",
"Balance", "Dishonesty",
"Decision-making", "Indecision",
"Solitude", "Isolation",
"Determination", "Impatience",
"Sorrow", "Forgiveness",
"Revelation", "Avoiding Disaster",
"Exploration", "Lack of Commitment",
"Refinement", "Lack of Focus",
"Choices", "Misalignment",
"Creativity", "Pessimism",
"Choices", "Clarity",
"Betrayal", "Resilience",
"Reevaluation", "Inflexibility",
"Calmness", "Moodiness",
"Emotional Fulfillment", "Blocked Emotions",
"Learning", "Procrastination",
"Victory", "Aggression",
"Teamwork", "Lack of Cooperation",
"Reunion", "Unrealistic Expectations",
"Compassion", "Manipulation",
"Subconscious", "Repressed Emotions",
"Guidance", "Unconventional",
"Planning", "Bad Decisions",
"Self-expression", "Ignorance",
"Romance", "Moodiness",
"New Beginnings", "Delays",
"Abundance", "Smothering",
"Resilience", "Fatigue",
"Defensiveness", "Exhaustion",
"Power", "Deception",
"Transformation", "Resistance",
"Independence", "Loneliness",
"Compassion", "Unresolved Pain",
"Authority", "Lack of Control",
"Family", "Disconnection",
"Curiosity", "Miscommunication",
"Stalemate", "Avoidance"
]

// 2 by 10 by 11 grid containing all 220 energies

// Starts like this:
// 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20
// 1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21 
export const energyGrid = [
  [
    [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20],
    [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21],
  ],
  [
    [22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42],
    [23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43],
  ],
  [
    [44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64],
    [45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65],
  ],
  [
    [66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86],
    [67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87],
  ],
  [
    [88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108],
    [89, 91, 93, 95, 97, 99, 101, 103, 105, 107, 109],
  ],
  [
    [110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130],
    [111, 113, 115, 117, 119, 121, 123, 125, 127, 129, 131],
  ],
  [
    [132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152],
    [133, 135, 137, 139, 141, 143, 145, 147, 149, 151, 153],
  ],
  [
    [154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174],
    [155, 157, 159, 161, 163, 165, 167, 169, 171, 173, 175],
  ],
  [
    [176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196],
    [177, 179, 181, 183, 185, 187, 189, 191, 193, 195, 197],
  ],
  [
    [198, 200, 202, 204, 206, 208, 210, 212, 214, 216, 218],
    [199, 201, 203, 205, 207, 209, 211, 213, 215, 217, 219],
  ],
];

export let energyMap = new Map<number, {value: string, group: number}>([
  [1, {value: "Beginnings", group: 2}],
  [2, {value: "Innocence", group: 2}],
  [3, {value: "Recklessness", group: 4}],
  [4, {value: "Naivety", group: 11}],
  [5, {value: "Manifestation", group: 2}],
  [6, {value: "Willpower", group: 10}],
  [7, {value: "Manipulation", group: 3}],
  [8, {value: "Trickery", group: 4}],
  [9, {value: "Intuition", group: 6}],
  [10, {value: "Mystery", group: 6}],
  [11, {value: "Secrets", group: 6}],
  [12, {value: "Disconnection", group: 1}],
  [13, {value: "Nurturing", group: 3}],
  [14, {value: "Abundance", group: 5}],
  [15, {value: "Dependence", group: 3}],
  [16, {value: "Neglect", group: 3}],
  [17, {value: "Authority", group: 4}],
  [18, {value: "Stability", group: 12}],
  [19, {value: "Tyranny", group: 4}],
  [20, {value: "Rigidity", group: 12}],
  [21, {value: "Tradition", group: 11}],
  [22, {value: "Spiritual guidance", group: 6}],
  [23, {value: "Dogmatism", group: 6}],
  [24, {value: "Rebellion", group: 4}],
  [25, {value: "Relationships", group: 3}],
  [26, {value: "Choices", group: 2}],
  [27, {value: "Disharmony", group: 12}],
  [28, {value: "Imbalance", group: 12}],
  [29, {value: "Triumph", group: 8}],
  [30, {value: "Loss of control", group: 4}],
  [31, {value: "Aggression", group: 1}],
  [32, {value: "Courage", group: 10}],
  [33, {value: "Patience", group: 10}],
  [34, {value: "Fear", group: 1}],
  [35, {value: "Impatience", group: 1}],
  [36, {value: "Introspection", group: 6}],
  [37, {value: "Guidance", group: 6}],
  [38, {value: "Isolation", group: 1}],
  [39, {value: "Withdrawal", group: 1}],
  [40, {value: "Luck", group: 7}],
  [41, {value: "Cycles", group: 6}],
  [42, {value: "Misfortune", group: 5}],
  [43, {value: "Resistance", group: 4}],
  [44, {value: "Fairness", group: 7}],
  [45, {value: "Balance", group: 12}],
  [46, {value: "Injustice", group: 4}],
  [47, {value: "Dishonesty", group: 7}],
  [48, {value: "Sacrifice", group: 2}],
  [49, {value: "Perspective", group: 6}],
  [50, {value: "Stagnation", group: 12}],
  [51, {value: "Indecision", group: 4}],
  [52, {value: "Transformation", group: 2}],
  [53, {value: "Endings", group: 2}],
  [54, {value: "Harmony", group: 12}],
  [55, {value: "Excess", group: 5}],
  [56, {value: "Temptation", group: 5}],
  [57, {value: "Bondage", group: 1}],
  [58, {value: "Release", group: 2}],
  [59, {value: "Enlightenment", group: 6}],
  [60, {value: "Sudden change", group: 2}],
  [61, {value: "Chaos", group: 12}],
  [62, {value: "Avoidance", group: 1}],
  [63, {value: "Hope", group: 1}],
  [64, {value: "Inspiration", group: 7}],
  [65, {value: "Despair", group: 1}],
  [66, {value: "Illusion", group: 6}],
  [67, {value: "Confusion", group: 1}],
  [68, {value: "Joy", group: 1}],
  [69, {value: "Success", group: 8}],
  [70, {value: "Negativity", group: 1}],
  [71, {value: "Depression", group: 1}],
  [72, {value: "Renewal", group: 2}],
  [73, {value: "Redemption", group: 2}],
  [74, {value: "Regret", group: 1}],
  [75, {value: "Denial", group: 1}],
  [76, {value: "Completion", group: 2}],
  [77, {value: "Wholeness", group: 2}],
  [78, {value: "Incompletion", group: 2}],
  [79, {value: "New beginnings", group: 2}],
  [80, {value: "Delay", group: 4}],
  [81, {value: "Lack of motivation", group: 10}],
  [82, {value: "Planning", group: 11}],
  [83, {value: "Expansion", group: 5}],
  [84, {value: "Progress", group: 8}],
  [85, {value: "Delays", group: 4}],
  [86, {value: "Frustration", group: 1}],
  [87, {value: "Celebration", group: 7}],
  [88, {value: "Conflict", group: 4}],
  [89, {value: "Competition", group: 4}],
  [90, {value: "Resolution", group: 4}],
  [91, {value: "Cooperation", group: 3}],
  [92, {value: "Recognition", group: 8}],
  [93, {value: "Failure", group: 8}],
  [94, {value: "Ego", group: 1}],
  [95, {value: "Perseverance", group: 10}],
  [96, {value: "Overwhelm", group: 1}],
  [97, {value: "Retreat", group: 1}],
  [98, {value: "Speed", group: 10}],
  [99, {value: "Action", group: 10}],
  [100, {value: "Resilience", group: 10}],
  [101, {value: "Persistence", group: 10}],
  [102, {value: "Exhaustion", group: 1}],
  [103, {value: "Defensiveness", group: 4}],
  [104, {value: "Burden", group: 5}],
  [105, {value: "Responsibility", group: 5}],
  [106, {value: "Enthusiasm", group: 10}],
  [107, {value: "Exploration", group: 11}],
  [108, {value: "Haste", group: 10}],
  [109, {value: "Lack of direction", group: 11}],
  [110, {value: "Energy", group: 10}],
  [111, {value: "Passion", group: 1}],
  [112, {value: "Impulsiveness", group: 10}],
  [113, {value: "Confidence", group: 1}],
  [114, {value: "Warmth", group: 1}],
  [115, {value: "Insecurity", group: 1}],
  [116, {value: "Jealousy", group: 1}],
  [117, {value: "Leadership", group: 4}],
  [118, {value: "Vision", group: 7}],
  [119, {value: "Arrogance", group: 1}],
  [120, {value: "Love", group: 3}],
  [121, {value: "Emotional fulfillment", group: 1}],
  [122, {value: "Blocked emotions", group: 1}],
  [123, {value: "Instability", group: 12}],
  [124, {value: "Partnership", group: 3}],
  [125, {value: "Connection", group: 3}],
  [126, {value: "Friendship", group: 3}],
  [127, {value: "Overindulgence", group: 5}],
  [128, {value: "Contemplation", group: 6}],
  [129, {value: "Apathy", group: 1}],
  [130, {value: "Renewed interest", group: 11}],
  [131, {value: "Loss", group: 5}],
  [132, {value: "Grief", group: 1}],
  [133, {value: "Acceptance", group: 2}],
  [134, {value: "Healing", group: 2}],
  [135, {value: "Nostalgia", group: 1}],
  [135, {value: "Nostalgia", group: 1}],
  [136, {value: "Reunion", group: 3}],
  [137, {value: "Stuck in the past", group: 1}],
  [138, {value: "Unrealistic expectations", group: 1}],
  [139, {value: "Clarity", group: 7}],
  [140, {value: "Decision", group: 4}],
  [141, {value: "Search for meaning", group: 6}],
  [142, {value: "Fear of change", group: 1}],
  [143, {value: "Satisfaction", group: 1}],
  [144, {value: "Wish fulfillment", group: 1}],
  [145, {value: "Discontent", group: 1}],
  [146, {value: "Greed", group: 1}],
  [147, {value: "Happiness", group: 1}],
  [148, {value: "Broken relationships", group: 3}],
  [149, {value: "Disillusionment", group: 1}],
  [150, {value: "Creativity", group: 7}],
  [151, {value: "Emotional immaturity", group: 1}],
  [152, {value: "Romance", group: 3}],
  [153, {value: "Idealism", group: 1}],
  [154, {value: "Moodiness", group: 1}],
  [155, {value: "Empathy", group: 1}],
  [156, {value: "Compassion", group: 1}],
  [157, {value: "Emotional manipulation", group: 3}],
  [158, {value: "Emotional balance", group: 12}],
  [159, {value: "Diplomacy", group: 4}],
  [160, {value: "Emotional detachment", group: 1}],
  [161, {value: "Breakthrough", group: 2}],
  [162, {value: "Heartbreak", group: 1}],
  [163, {value: "Sorrow", group: 1}],
  [164, {value: "Forgiveness", group: 4}],
  [165, {value: "Rest", group: 6}],
  [166, {value: "Meditation", group: 6}],
  [167, {value: "Restlessness", group: 1}],
  [168, {value:"Burnout", group: 1}],
  [169, {value: "Defeat", group: 8}],
  [170, {value: "Reconciliation", group: 4}],
  [171, {value: "Transition", group: 2}],
  [172, {value: "Deception", group: 4}],
  [173, {value: "Strategy", group: 4}],
  [174, {value: "Honesty", group: 7}],
  [175, {value: "Exposure", group: 4}],
  [176, {value: "Restriction", group: 5}],
  [177, {value: "Anxiety", group: 1}],
  [178, {value: "Recovery", group: 2}],
  [179, {value: "Betrayal", group: 3}],
  [180, {value: "Curiosity", group: 11}],
  [181, {value: "Communication", group: 7}],
  [182, {value: "Gossip", group: 3}],
  [183, {value: "Ambition", group: 10}],
  [184, {value: "Wisdom", group: 11}],
  [185, {value: "Independence", group: 2}],
  [186, {value: "Coldness", group: 1}],
  [187, {value: "Intellect", group: 11}],
  [188, {value: "Prosperity", group: 9}],
  [189, {value: "Opportunity", group: 9}],
  [190, {value: "Missed opportunity", group: 9}],
  [191, {value: "Financial loss", group: 9}],
  [192, {value: "Adaptability", group: 2}],
  [193, {value: "Teamwork", group: 3}],
  [194, {value: "Collaboration", group: 3}],
  [195, {value: "Lack of cooperation", group: 3}],
  [196, {value: "Disorganization", group: 3}],
  [197, {value: "Control", group: 4}],
  [198, {value: "Hardship", group: 5}],
  [199, {value: "Generosity", group: 5}],
  [200, {value: "Charity", group: 5}],
  [201, {value: "Selfishness", group: 1}],
  [202, {value: "Debt", group: 9}],
  [203, {value: "Growth", group: 2}],
  [204, {value: "Skill", group: 11}],
  [205, {value: "Dedication", group: 10}],
  [206,{value: "Lack of focus", group: 1}],
  [207, {value: "Perfectionism", group: 1}],
  [208, {value: "Self-Sufficiency", group: 2}],
  [209, {value: "Financial dependency", group: 9}],
  [210, {value: "Wealth", group: 9}],
  [211, {value: "Legacy", group: 9}],
  [212, {value: "Financial instability", group: 9}],
  [213, {value: "Family conflict", group: 3}],
  [214, {value: "Learning", group: 11}],
  [215, {value: "Procrastination", group: 1}],
  [216, {value: "Lack of progress", group: 8}],
  [217, {value: "Laziness", group: 1}],
  [218, {value: "Practicality", group: 2}],
  [219, {value: "Materialism", group: 5}],
  [220, {value: "Stubbornness", group: 1}]
]);

export let energyGroups = new Map<number, {color:string, title:string}>([
  [1, {"color":"#B99FE4", "title":"Emotional States"}],
  [2, {"color":"#2ECC71", "title":"Personal Growth and Transformation"}],
  [3, {"color":"#FF00FF", "title":"Relationships and Interactions"}],
  [4, {"color":"#FF0E00", "title":"Conflict and Resolution"}],
  [5, {"color":"#FF851B", "title":"Abundance and Scarcity"}],
  [6, {"color":"#AC50EF", "title":"Inner Exploration and Spirituality"}],
  [7, {"color":"#1E90FF", "title":"Communication and Expression"}],
  [8, {"color":"#FFD700", "title":"Success and Failure"}],
  [9, {"color":"#228B22", "title":"Material and Financial Aspects"}],
  [10, {"color":"#FF69B4", "title":"Motivation and Drive:"}],
  [11, {"color":"#B92347", "title":"Learning and Knowledge"}],
  [12, {"color":"#20B2AA", "title":"Balance and Imbalance:"}]
]);

