export const energies = new Map([  ['Beginnings', ['The Fool', 'Death']],
['Adventure', ['The Fool', 'The World']],
['Creativity', ['The Magician', 'The Empress', 'The Sun']],
['Communication', ['The Magician', 'The High Priestess']],
['Intuition', ['The High Priestess', 'Strength', 'The Moon']],
['Wisdom', ['The High Priestess', 'The Hermit', 'The Moon']],
['Mystery', ['The High Priestess', 'The Moon']],
['Nurturing', ['The Empress', 'Strength']],
['Abundance', ['The Empress', 'The World']],
['Authority', ['The Emperor', 'The Hierophant']],
['Stability', ['The Emperor', 'The World']],
['Discipline', ['The Emperor', 'Strength']],
['Tradition', ['The Hierophant', 'The Hermit']],
['Guidance', ['The Hierophant', 'The Hermit', 'The Star']],
['Education', ['The Hierophant', 'The Hermit']],
['Relationships', ['The Lovers', 'The Empress']],
['Harmony', ['The Lovers', 'The Chariot', 'Temperance']],
['Choice', ['The Lovers', 'The Hanged Man']],
['Determination', ['The Chariot', 'Strength']],
['Progress', ['The Chariot', 'The Wheel of Fortune']],
['Courage', ['Strength', 'The Hanged Man']],
['Solitude', ['The Hermit', 'The Hanged Man']],
['Reflection', ['The Hermit', 'The Moon']],
['Cycles', ['The Wheel of Fortune', 'The World']],
['Destiny', ['The Wheel of Fortune', 'Judgment']],
['Balance', ['Justice', 'Temperance']],
['Fairness', ['Justice', 'The Lovers']],
['Truth', ['Justice', 'The Moon']],
['Surrender', ['The Hanged Man', 'The Tower']],
['Transformation', ['Death', 'The Tower']],
['Hope', ['The Star', 'The Sun']],
['Inspiration', ['The Star', 'The Magician']],
['Renewal', ['Judgment', 'The Sun']],
['Redemption', ['Judgment', 'The Hanged Man']],
['Temptation', ['The Devil', 'The Lovers']],
['Obsession', ['The Devil', 'The Moon']],
['Exploration', ['The Fool', 'The World']],
['Transition', ['Death', 'The Wheel of Fortune']],
['Upheaval', ['The Tower', 'The Wheel of Fortune']],
['Constraint', ['The Devil', 'The Hanged Man']]
]);

export const energyList = Array.from(energies.keys());