export type ReadingSpreadType = {
  key?: string;
  name: string;
  positions: string[];
  instructions: string[];
  placeholders?: string[];
};

export default new Map<string, ReadingSpreadType>([
  ["qa", {
    key: "qa",
    name: "Question & Answer",
    positions: [""],
    instructions: [""],
    placeholders: ["How can I...",
    "What should I...",
    "Where will...",
    "Who is influencing...",
    "Why am I feeling...",
    "What is the purpose of...",
    "How does this situation...",
    "What is the potential outcome if...",
    "Who should I...",
    "What is the underlying issue of...",
    "How can I improve...",
    "What is the best way to...",
    "What is the hidden factor in...",
    "Where should I...",
    "Why is this happening...",
    "What is the significance of...",
    "How can I overcome...",
    "What is the likely result of...",
    "Who is the key person in...",
    "What is the root cause of...",
    "How can I resolve...",
    "What is the impact of...",
    "Where is the...",
    "Why does...",
    "What is the meaning of...",
    "How can I utilize...",
    "What is the role of...",
    "Who is the...",
    "What is the potential of...",
    "How can I harness..."]
  }],
  ["pc", {
    key: "pc",
    name: "Pros & Cons",
    positions: ["Pros", "Cons"],
    instructions: ["Write a bullet point list of the positives of the situation", "Write a bullet point list of the negatives of the situation"],
    placeholders: ["Could you reveal the pros and cons of...",
    "What might be the positive and negative outcomes if...",
    "Can you show the benefits and drawbacks of...",
    "Could you illustrate the advantages and disadvantages in...",
    "What are the potential rewards and risks associated with...",
    "Can you highlight the positive and negative aspects of...",
    "What might be the gains and losses from...",
    "Could you detail the strengths and weaknesses in...",
    "What are the potential upsides and downsides to...",
    "Can you outline the potential boons and banes of...",
    "What might be the positive and negative implications if...",
    "Could you explain the potential assets and liabilities of...",
    "What are the potential opportunities and pitfalls in...",
    "Can you clarify the potential pluses and minuses of...",
    "What might be the potential benefits and detriments when...",
    "Could you elaborate on the potential advantages and setbacks of...",
    "What are the potential rewards and hazards in...",
    "Can you provide insight into the potential upsides and drawbacks when...",
    "What might be the potential boons and drawbacks in...",
    "Could you shed light on the potential positives and negatives of...",
    "What are the potential assets and drawbacks when...",
    "Can you disclose the potential opportunities and risks in...",
    "What might be the potential pluses and minuses when...",
    "Could you unveil the potential pros and cons when...",
    "What are the potential benefits and disadvantages in...",
    "Can you reveal the potential advantages and hazards of...",
    "What might be the potential gains and pitfalls if...",
    "Could you detail the potential rewards and risks when...",
    "What are the potential upsides and downsides in..."]
  }],
  ["ppf", {
    key: "ppf",
    name: "Past, Present & Future",
    positions: ["Past", "Present", "Future"],
    instructions: [
      // "Draw any card in any orientation and tell the aspects of it that relate to the past of the situation presented in the question.",
      // "Draw any card in any orientation and tell the aspects of it that relate to the present of the situation presented in the question.",
      // "Draw any card in any orientation and tell the aspects of it that relate to the future of the situation presented in the question."
      "none",
      "none",
      "start with a short phrase telling the story at a glance"
    ],
    placeholders: ["What was the root cause of...",
    "How did my past actions...",
    "What were the key influences in my past that...",
    "What lessons from my past can...",
    "How does my present situation...",
    "What is the current state of...",
    "What are the key factors influencing my present...",
    "What should I focus on in the present to...",
    "How might my future be influenced by...",
    "What potential outcomes can I expect in the future if...",
    "What steps should I take in the present to influence my future...",
    "What does my future hold if...",
    "How can I use my past experiences to...",
    "What changes in the present could...",
    "What might be the future implications of...",
    "How can my past inform my present...",
    "What is the trajectory from my present to...",
    "How can I change my future by...",
    "What does my past suggest about my present...",
    "What can my present tell me about potential future...",
    "How can my past decisions affect my future...",
    "What is the connection between my present and...",
    "How can I leverage my present to improve my future...",
    "What does the future look like based on my present...",
    "How can I learn from my past to better my future..."]
  }]
])